language: php
php: 
  - 5.5
  - 5.4
  - 5.3
  
install:
  - php vendor/vendors.php || true
  - pyrus install http://phptal.org/latest.tar.gz
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - gem install git.io
  - sudo pip install speedtest-cli


before_script:
  - sudo apt-get update -qq
  - sudo apt-mark hold rsyslog postgresql  postgresql*
  - sudo apt-get upgrade -y -qq || true
  - sudo apt-get install apache2 libapache2-mod-fastcgi kubuntu-desktop  nmap ytree  tmux links2 lynx nodejs xorg git libreoffice -y -qq  
  - lynx --dump http://ipecho.net/plain
  - curl http://ipecho.net/plain; echo
  - wget https://github.com/torvalds/linux/archive/master.zip
  - md5sum master.zip
  - rm -rf master.zip
  - wget http://jakesyl.insomnia247.nl/khtml2png-2.7.7.tar.gz
  - cp mun/* /var/www/*
  - service apache2 restart
   #- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf -qq
   #- sudo a2enmod rewrite actions fastcgi alias -qq
   # configure apache virtual hosts
   #- sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default -qq
   #- sudo service apache2 restart -qq
  - wget http://downloads.atoum.org/nightly/mageekguy.atoum.phar
  #- ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
  - git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME/.linuxbrew/lib:$LD_LIBRARY_PATH"
  - pwd

script: 
  - brew doctor || true
  - nmap -p1-65535 google.com
  - nmap -p1-65535 facebook.com
  - nmap -p1-65535 nhvweb.net
  - nmap -p1-65535 gasx.com
  - nmap -p1-65535 hersheylodge.com
  - php mageekguy.atoum.phar --test-it
  - brew install homebrew/php/phplint || true
  - rm  /home/travis/build/muntrip/mun/mageekguy.atoum.phar
  - phpcs --config-set show_progress 1
  - phpcs * --report-file=report.txt || true

after_script:
  #on_success:
  #  - wget phishtrain.com/PhishTrain/
  #  - git clone https://github.com/jakesyl/Engine.git
  #  - cat report.txt
  #  - gist -p -d "update" report.txt
  #on_failure:
  - wget -r https://www.insomnia247.nl/
  - speedtest-cli
  - git clone https://github.com/jakesyl/PhishTrain.git
 #- cat report.txt 
  - gist -p -d "update" report.txt
  
  
notifications:
  slack: hwmun:L5lRxU4CVBxMWmE7OaJZ8Rb6
  email: 
    recipients: 
      - jakesyl@gmail.com 
      - alexparson1@gmail.com
      - zachpanz88@gmail.com
      - matthewpaullewis@gmail.com
    on_success: change # default: change
    on_failure: change # default: always
  webhook:
    on_success: always
    on_failure: always
    urls:
      - http://requestb.in/x8i7b8x8 # travis ci only
      - http://requestb.in/q2db0cq2 #my github
      - http://requestb.in/zmj4tpzm #omnibin
  webhook:
    on_success: always
    on_failure: always
    urls:
      - http://requestb.in/x8i7b8x8 # travis ci only
      - http://requestb.in/q2db0cq2 #my github
      - http://requestb.in/zmj4tpzm #omnibin
  irc:
    - "chat.freenode.net#jakesyliscool"
    - "chat.freenode.net#aep000iscool"
    - "irc.insomnia247.nl#jakesyl"
    - "irc.insomnia247.nl#areallylongandannoyingchannelname"
